### ISSUE TITLE
Seeking mentor for Google Summer of Code 2016 for Social API module

### ISSUE THREAD

**Issue by dahacouk** [drupalsocialinitiative/social_api#3]
Hello @drupalsocialinitiative/owners !

We are looking for a technical mentor for the Social API project for the GSoC (Google Summer of Code) 2016 to work alongside [Daniel Harris](https://www.drupal.org/u/dahacouk)/@dahacouk . We are currently working to get the [Social API](https://www.drupal.org/project/social_api) module to be one of the projects that Google Summer of Code students will work on during this summer: https://groups.drupal.org/node/508466#project7 . [Valentin Sánchez](https://www.drupal.org/u/gvso)/@gvso is interested in working on this project as the student. Google Summer of Code is a global program focused on bringing more student developers into open source software development. Students work with an open source organization on a 3 month programming project during their break from school. More about Google Summe of Code program: https://summerofcode.withgoogle.com/ . If you are interested please reply to this post (and/or reply to https://groups.drupal.org/node/509411) or contact me via Skype "dahacouk" and I'll add you to the Skype group. Other comments welcome.

Cheers Daniel

**Comment by RoySegall** [comment]
Amm.. this mean we need to mentor him via skype? be in a conference? What
the issue on this?

**Comment by GVSO** [comment]
Hi! Google Summer of Code (GSoC) is a program in which university students work with an open source organization for around 3 month, in which they develop a project inside the community. I'm interested in working on the Social API project, but the program requires that students need to be guided by a mentor, who must be someone in the organization (in this case Drupal). I'm working with David right now, but it would be much better if we also have another/other mentor(s) with a technical background.

Mentors are mostly in charge of guide students, review their progress and evaluate the final project.

**Comment by mgifford** [comment]
Wish we could help. Just not a good time for us to jump in on this.

**Comment by RoySegall** [comment]
I don't know if I could help all the way but what the scale of the mentoring for this one?

**Comment by GVSO** [comment]
What do you mean with "the scale of the mentoring"?. This is the document in which I explain how the social api will work and the expected deliverables per week [https://goo.gl/Q5Otlg](https://goo.gl/Q5Otlg). The mentor should keep track of the student's work. This means that the student is who must do most (if not all) of the work. 

Furthermore, I already have experience working with Drupal, so I'm likely to finish the project without major drawbacks, but I still need another mentor with a technical background.

**Comment by dahacouk** [comment]
I am extremely excited to announce that Google has just announced that it is funding Valentin Sánchez to work on the Drupal Social API via Google Summer of Code (GSoC) 2016:
https://summerofcode.withgoogle.com/organizations/5879646751031296/#5689394501517312

I've set up this Google mailing list to celebrate:
https://groups.google.com/d/forum/drupal-social-initiative

And here are some other ways to participate in the project:
https://groups.drupal.org/social-initiative
https://www.drupal.org/project/social_api
https://github.com/drupalsocialinitiative
Google Drive: https://goo.gl/YDvjxL - See "Read Me First"

Please invite Drupal users and developers who you think would be interested in helping the Drupal Social Initiative to create the Drupal Social API.

Cheers Daniel

**Comment by dahacouk** [comment]
So, that means this issue is complete.
